//
// Copyright © 2016 Ikey Doherty
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package ylib

import (
	"github.com/go-yaml/yaml"
	"io/ioutil"
)

// MarshalledYpkg is autogenerated by the tooling solely for writing to disk
type MarshalledYpkg struct {
	Name        string
	Version     string
	Homepage    string
	License     []string
	Summary     string
	Description string
	Source      map[string]string
}

// WriteYpkg will attempt to write the MarshalledYpkg to a file
func WriteYpkg(path string, pkg *MarshalledYpkg) error {
	var output []byte
	var err error

	if output, err = yaml.Marshal(pkg); err != nil {
		return err
	}

	return ioutil.WriteFile(path, output, 00644)
}
